version: '3'
services:
    php-dev:
        image: 'webdevops/php-nginx-dev:8.0'
        user: '${UID:-1000}'
        container_name: '${APP_NAME}-php'
        working_dir: /var/www/html
        environment:
            - WEB_DOCUMENT_ROOT=/var/www/html/public
        volumes:
            - './:/var/www/html'
            - '~/.ssh:/home/application/.ssh'
            - '~/.ssh:/root/.ssh'
        networks:
            - app
networks:
    app:
        driver: bridge
